### ISSUE TITLE
Allow calling raw API

### ISSUE THREAD

**Issue by kgtkr** [egg-mode-rs/egg-mode#83]
Currently this library can only call fixed endpoints with fixed parameters.
But this does not allow you to use hidden APIs and parameters
So I want a function that returns the `serde_json::Value` by freely passing the URL and parameters

**Comment by adwhit** [comment]
I think this is reasonable. It probably amount to exposing the `raw_request` and `request_with_json_response` functions.
https://github.com/QuietMisdreavus/twitter-rs/blob/master/src/common/response.rs#L92-L125

**Comment by QuietMisdreavus** [comment]
I would say this is tied to https://github.com/QuietMisdreavus/twitter-rs/issues/32, since exposing the raw authentication primitives would allow you to assemble "raw" requests like you want. I would probably want to have some kind of wrapper between `auth::{get, post, post_json}` and the response functions in `common::response` as the public "raw" API. Should we also expose all the URLs in the `links` module as well? That way people could use the existing URLs that we have if they aren't wrapping an unbound API.

**Comment by QuietMisdreavus** [comment]
Update: i've posted https://github.com/egg-mode-rs/egg-mode/pull/91 which exposes just enough internals to enable calling arbitrary endpoints. If you'd like, you can give it a look - hopefully this should serve your purposes.
