### ISSUE TITLE
Serialize for Tweet?

### ISSUE THREAD

**Issue by PSeitz** [egg-mode-rs/egg-mode#90]
It seems for Tweet only Deserialize is implemented and not Serialize
https://github.com/egg-mode-rs/egg-mode/blob/master/src/tweet/mod.rs#L236

**Comment by adwhit** [comment]
Could you outline your use-case? It would not be possible to serialize the tweet in the exact form that it is received from the twitter servers as it is a lossy deserialization.

If you just want to dump the tweet e.g. to JSON for storage, I agree `Serialize` would be useful. Though, it might be better to create your own type that only plucks out the values you need to store.

**Comment by PSeitz** [comment]
Yes, storing them in a json format is the use case. Copying the values in a struct is what I'm doing currently, but it would be nice to have a default out of the box, since I guess this use case is quite common.

**Comment by hdevalence** [comment]
I'd also like to have a `Serialize` implementation (use-case: caching tweets to avoid hitting API limits too much). I'd be happy to contribute a PR if there was an acceptable design for the implementation.

**Comment by QuietMisdreavus** [comment]
I had an idea on how to do this somewhat efficiently, and posted PR #99 with the implementation. I asked around and people pointed me to `#[serde(untagged)]`, which enables you to load/save an enum solely by the contents of its variants, instead of a tag value. This seemed to work perfectly, with the drawback that error messages become opaque. Does this work for y'all?
